---
title: "20180716_月报分析通用模板"
author: "wzy"
date: "2018年7月16日"
output:
  word_document: default
  html_document: default
---

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F,message = F,warning = F)
```

```{r}
options(stringsAsFactors = F)
options(digits = 3)
rm(list = ls())
source("D:\\R\\packages\\Mreport\\scripts\\caculate.R", encoding = "utf-8")
source("D:\\R\\packages\\Mreport\\scripts\\select.R", encoding = "utf-8")
```

```{r}
library(Mreport)
library(plyr)
library(ggplot2)
library(reshape2)
library(knitr)
library(leaflet)
library(leafletCN)
```

```{r}
load_base()
load_sample_base()
```

```{r include=FALSE}
jdnew <- read.csv("D:\\data\\sx_raw\\交调数据\\jd2018_07_2.csv")
jdlast <- read.csv("D:\\data\\sx_raw\\交调数据\\jd2018_06_new.csv")
jdprevious <- read.csv("D:\\data\\sx_raw\\交调数据\\jd2017_07_2.csv")
```

```{r include=FALSE}
jdnews <- handle_gather(jdnew)
jdlasts <- handle_gather(jdlast)
jdpreviouss <- handle_gather(jdprevious)
usefulstation <- intersect(jdnews$index,jdlasts$index)
jdnews <- jdnews[jdnews$index %in% usefulstation,]
jdlasts <- jdlasts[jdlasts$index %in% usefulstation,]
jdpreviouss <- jdpreviouss[jdpreviouss$index %in% usefulstation,]
```

## 2. 全国公路网

### 2.1 机动车

```{r}
totalnewcars <- ddply(jdnews,"level",summarise,Wmean = weighted.mean(cars,w=mileage))
totalpreviouscars <- ddply(jdpreviouss,"level",summarise,Wmean = weighted.mean(cars,w=mileage))
x <- caculate_increaseratio(totalnewcars,totalpreviouscars)
totallastcars <- ddply(jdlasts,"level",summarise,Wmean = weighted.mean(cars,w=mileage))
y <- caculate_increaseratio(totalnewcars,totallastcars)
z <- merge_outcome(totalnewcars,x,y,by="level")
temp <- z[3,]
z[3,] <- z[4,]
z[4,] <- temp
names(z) <- c("道路等级","本月","同比","环比")
kable(z)
```

### 2.2 客车

```{r}
totalnewpasscars <- ddply(jdnews,"level",summarise,Wmean = weighted.mean(passenger_cars,w=mileage))
totalpreviouspasscars <- ddply(jdpreviouss,"level",summarise,Wmean = weighted.mean(passenger_cars,w=mileage))
x <- caculate_increaseratio(totalnewpasscars,totalpreviouspasscars)
totallastpasscars <- ddply(jdlasts,"level",summarise,Wmean = weighted.mean(passenger_cars,w=mileage))
y <- caculate_increaseratio(totalnewpasscars,totallastpasscars)
z <- merge_outcome(totalnewpasscars,x,y,by="level")
temp <- z[3,]
z[3,] <- z[4,]
z[4,] <- temp
names(z) <- c("道路等级","本月","同比","环比")
kable(z)
```

### 2.3 货车

```{r}
totalnewfrecars <- ddply(jdnews,"level",summarise,Wmean = weighted.mean(freight_cars,w=mileage))
totalpreviousfrecars <- ddply(jdpreviouss,"level",summarise,Wmean = weighted.mean(freight_cars,w=mileage))
x <- caculate_increaseratio(totalnewfrecars,totalpreviousfrecars)
totallastfrecars <- ddply(jdlasts,"level",summarise,Wmean = weighted.mean(freight_cars,w=mileage))
y <- caculate_increaseratio(totalnewfrecars,totallastfrecars)
z <- merge_outcome(totalnewfrecars,x,y,by="level")
temp <- z[3,]
z[3,] <- z[4,]
z[4,] <- temp
names(z) <- c("道路等级","本月","同比","环比")
kable(z)
```

## 3. 通道分析

### 3.1 十横通道

#### 机动车

```{r}
horizonnew <- caculate_carsmean(jd = jdnews,attsname = "horizon10")
horizonprevious <- caculate_carsmean(jd = jdpreviouss,attsname = "horizon10")
x1 <- caculate_increaseratio(horizonnew,horizonprevious)
horizonlast <- caculate_carsmean(jd = jdlasts,attsname = "horizon10")
x2 <- caculate_increaseratio(horizonnew,horizonlast)
t <- merge_outcome(horizonnew,x1,x2,bywhat = "horizon10")
names(t) <- c("十横通道","月平均日交通量","同比","环比")
kable(t)
```

#### 客车

```{r}
horizonnew <- caculate_passcarsmean(jd = jdnews,attsname = "horizon10")
horizonprevious <- caculate_passcarsmean(jd = jdpreviouss,attsname = "horizon10")
x1 <- caculate_increaseratio(horizonnew,horizonprevious)
horizonlast <- caculate_passcarsmean(jd = jdlasts,attsname = "horizon10")
x2 <- caculate_increaseratio(horizonnew,horizonlast)
t <- merge_outcome(horizonnew,x1,x2,bywhat = "horizon10")
names(t) <- c("十横通道","月平均日交通量","同比","环比")
kable(t)
```

#### 货车

```{r}
horizonnew <- caculate_frecarsmean(jd = jdnews,attsname = "horizon10")
horizonprevious <- caculate_frecarsmean(jd = jdpreviouss,attsname = "horizon10")
x1 <- caculate_increaseratio(horizonnew,horizonprevious)
horizonlast <- caculate_frecarsmean(jd = jdlasts,attsname = "horizon10")
x2 <- caculate_increaseratio(horizonnew,horizonlast)
t <- merge_outcome(horizonnew,x1,x2,bywhat = "horizon10")
names(t) <- c("十横通道","月平均日交通量","同比","环比")
kable(t)
```

### 3.2 十纵通道

#### 机动车

```{r}
verticalnew <- caculate_carsmean(jd = jdnews,attsname = "vertical10")
verticalprevious <- caculate_carsmean(jd = jdpreviouss,attsname = "vertical10")
x1 <- caculate_increaseratio(verticalnew,verticalprevious)
verticallast <- caculate_carsmean(jd = jdlasts,attsname = "vertical10")
x2 <- caculate_increaseratio(verticalnew,verticallast)
t <- merge_outcome(verticalnew,x1,x2,bywhat = "vertical10")
names(t) <- c("十纵通道","月平均日交通量","同比","环比")
kable(t)
```

#### 客车

```{r}
verticalnew <- caculate_passcarsmean(jd = jdnews,attsname = "vertical10")
verticalprevious <- caculate_passcarsmean(jd = jdpreviouss,attsname = "vertical10")
x1 <- caculate_increaseratio(verticalnew,verticalprevious)
verticallast <- caculate_passcarsmean(jd = jdlasts,attsname = "vertical10")
x2 <- caculate_increaseratio(verticalnew,verticallast)
t <- merge_outcome(verticalnew,x1,x2,bywhat = "vertical10")
names(t) <- c("十纵通道","月平均日交通量","同比","环比")
kable(t)
```

#### 货车

```{r}
verticalnew <- caculate_frecarsmean(jd = jdnews,attsname = "vertical10")
verticalprevious <- caculate_frecarsmean(jd = jdpreviouss,attsname = "vertical10")
x1 <- caculate_increaseratio(verticalnew,verticalprevious)
verticallast <- caculate_frecarsmean(jd = jdlasts,attsname = "vertical10")
x2 <- caculate_increaseratio(verticalnew,verticallast)
t <- merge_outcome(verticalnew,x1,x2,bywhat = "vertical10")
names(t) <- c("十纵通道","月平均日交通量","同比","环比")
kable(t)
```

### 3.3 典型通道分省交通情况

#### 3.3.1 沪昆通道

```{r}
t <- typicalroute_horizon(jdnews,jdpreviouss,"上海-瑞丽")
names(t) <- c("省份","月平均日交通量","同比")
t %>% kable()
```

#### 3.3.2 陆桥通道

```{r}
t <- typicalroute_horizon(jdnews,jdpreviouss,"连云港-霍尔果斯")
names(t) <- c("省份","月平均日交通量","同比")
t %>% kable()
```

#### 3.3.3 沿江通道

```{r}
t <- typicalroute_horizon(jdnews,jdpreviouss,"上海-樟木")
names(t) <- c("省份","月平均日交通量","同比")
t %>% kable()
```

#### 3.3.4 天津至红其拉甫通道

```{r}
t <- typicalroute_horizon(jdnews,jdpreviouss,"天津-红其拉甫")
names(t) <- c("省份","月平均日交通量","同比")
t %>% kable()
```

#### 3.3.5 京沪通道

```{r}
t <- typicalroute_vertical(jdnews,jdpreviouss,"北京-上海")
names(t) <- c("省份","月平均日交通量","同比")
t %>% kable()
```

#### 3.3.6 沿海通道

```{r}
t <- typicalroute_vertical(jdnews,jdpreviouss,"同江-三亚")
names(t) <- c("省份","月平均日交通量","同比")
t %>% kable()
```

#### 3.3.7 黑河至港澳台通道

```{r}
t <- typicalroute_vertical(jdnews,jdpreviouss,"黑河-港澳台")
names(t) <- c("省份","月平均日交通量","同比")
t %>% kable()
```


## 4. 集疏运通道分析

### 4.1 疏港公路分析

```{r}
portroadnew <- caculate_frecarsmean(jdnews,attsname = "portroad")
portroadprevious <- caculate_frecarsmean(jdpreviouss,attsname = "portroad")
x1 <- caculate_increaseratio(portroadnew,portroadprevious)
portroadlast <- caculate_frecarsmean(jdlasts,attsname = "portroad")
x2 <- caculate_increaseratio(portroadnew,portroadlast)
t <- merge_outcome(portroadnew,x1,x2,bywhat = "portroad")
t$portroad <- substr(t$portroad,1,nchar(t$portroad)-1)
t <- t[order(t$now,decreasing = T),]
kable(t)
```

```{r eval=FALSE}
t <- merge(station_plot,sample_base$portroad,by.x = "popup",by.y = "index",all.y = T)
p <- jdnews[,c(1,10,11,12)]
tt <- merge(t,p,by.x = "popup",by.y="index")
tt <- tt[,-2]
names(tt)[4] <- "label"
```

```{r}
port <- tt
port <- port[,c(2,3,4,7)]
ttt <- aggregate(port,by=list(port$label),FUN=mean)
ttt$label <- ttt$Group.1
```


```{r}
leaflet(ttt) %>% addProviderTiles("CartoDB.PositronNoLabels") %>% 
  addCircles(label = ~label,lng = ~lng,lat = ~lat,
             radius = ~cars/3,stroke = F, fillOpacity = 1, fillColor ="red",
             labelOptions = labelOptions(noHide = T,textsize=10))
```


### 4.2 机场连接公路分析

```{r}
airportnew <- caculate_carsmean(jdnews,attsname = "airport")
airportprevious <- caculate_carsmean(jdpreviouss,attsname = "airport")
x1 <- caculate_increaseratio(airportnew,airportprevious)
airportlast <- caculate_carsmean(jdlasts,attsname = "airport")
x2 <- caculate_increaseratio(airportnew,airportlast)
t <- merge_outcome(airportnew,x1,x2,bywhat = "airport")
#t$airport <- substr(t$airport,1,nchar(t$airport)-1)
t <- t[order(t$now,decreasing = T),]
kable(t)
```

```{r eval=FALSE}
t <- merge(station_plot,sample_base$airport,by.x = "popup",by.y = "index",all.y = T)
p <- jdnews[,c(1,10,11,12)]
tt <- merge(t,p,by.x = "popup",by.y="index")
tt <- tt[,-2]
names(tt)[4] <- "label"
leaflet(tt) %>% addTiles() %>% 
  addCircles(label = ~label,lng = ~lng,lat = ~lat,popup = ~popup,
             radius = ~cars/5,stroke = F, fillOpacity = 1, fillColor ="red")
```

## 5. 城市群分析

站点在各个城市群的分布如下：

```{r eval=FALSE}
t <- merge(station_plot,sample_base$citygroup2,by.x = "popup",by.y = "index",all.y = T)
names(t)[5] <- "type"
geo_pointplot(t,na.rm=T,type = T)
```

### 5.1 总体

```{r}
x <- caculate_carsmean(jdnews,"citygroup2")
```

```{r}
x1 <- caculate_increaseratio(caculate_carsmean(jdnews,"citygroup2"),
                       caculate_carsmean(jdpreviouss,"citygroup2"))
```

```{r}
x2 <- caculate_increaseratio(caculate_carsmean(jdnews,"citygroup2"),
                       caculate_carsmean(jdlasts,"citygroup2"))
```

```{r}
t <- merge_outcome(x,x1,x2,bywhat = "citygroup2")
names(t) <- c("城市群","月平均日交通量","同比","环比")
kable(t)
```


### 5.2 客车

```{r}
x <- caculate_passcarsmean(jdnews,"citygroup2")
```

```{r}
x1 <- caculate_increaseratio(caculate_passcarsmean(jdnews,"citygroup2"),
                       caculate_passcarsmean(jdpreviouss,"citygroup2"))
```

```{r}
x2 <- caculate_increaseratio(caculate_passcarsmean(jdnews,"citygroup2"),
                       caculate_passcarsmean(jdlasts,"citygroup2"))
```

```{r}
t <- merge_outcome(x,x1,x2,bywhat = "citygroup2")
names(t) <- c("城市群","月平均日交通量","同比","环比")
kable(t)
```

### 5.3 货车

```{r}
x <- caculate_frecarsmean(jdnews,"citygroup2")
```

```{r}
x1 <- caculate_increaseratio(caculate_frecarsmean(jdnews,"citygroup2"),
                       caculate_frecarsmean(jdpreviouss,"citygroup2"))
```

```{r}
x2 <- caculate_increaseratio(caculate_frecarsmean(jdnews,"citygroup2"),
                       caculate_frecarsmean(jdlasts,"citygroup2"))
```

```{r}
t <- merge_outcome(x,x1,x2,bywhat = "citygroup2")
names(t) <- c("城市群","月平均日交通量","同比","环比")
kable(t)
```

## 6. 分省情况

### 6.1 总体情况

```{r eval=FALSE}
caculate_carsmean(jdnews,"province") %>% 
geojsonMap(mapName = "China")
```

```{r}
x <- caculate_carsmean(jdnews,"province")
y <- caculate_increaseratio(caculate_carsmean(jdnews,"province"),
                       caculate_carsmean(jdpreviouss,"province"))
z <- caculate_increaseratio(caculate_carsmean(jdnews,"province"),
                       caculate_carsmean(jdlasts,"province"))
t <- merge_outcome(x,y,z,bywhat = "province")
names(t) <- c("省级行政区","月平均日交通量","同比","环比")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

```{r}
caculate_carsmean(jdnews,"province") %>% gg_boxplot(xangle = 90,xlabname = "省级行政区",
                                                    ylabname="月平均日机动车交通量")
ggsave(filename = "D:\\交大云同步\\实习\\06_月度分析报告\\7月分析\\绘图\\省级机动车.jpg",dpi=600)
```


### 6.2 分道路等级情况

#### 本月

```{r, results="asis"}
provincenewcars <- caculate_level_carsmean(jdnews,"province")
provincenewcars$province <- factor(provincenewcars$province,ordered=T,levels = province_level)
provincenewcars <- provincenewcars[order(provincenewcars$province),c("province","国家高速","普通国道","省级高速","普通省道")]
kable(provincenewcars)
```

#### 同比

```{r}
provincepreviouscars <- caculate_level_carsmean(jdpreviouss,"province")
provincepreviouscars <- provincepreviouscars[,c("province","国家高速","普通国道","省级高速","普通省道")]
t <- caculate_increaseratio(provincenewcars,provincepreviouscars)
t$province <- factor(t$province,ordered=T,levels = province_level)
kable(t[order(t$province),])
```

#### 环比

```{r}
provincelastcars <- caculate_level_carsmean(jdlasts,"province")
provincelastcars <- provincelastcars[,c("province","国家高速","普通国道","省级高速","普通省道")]
t <- caculate_increaseratio(provincenewcars,provincelastcars)
t$province <- factor(t$province,ordered=T,levels = province_level)
kable(t[order(t$province),])
```

### 6.3 客车交通量情况

```{r eval=FALSE}
caculate_passcarsmean(jdnews,"province") %>% 
geojsonMap(mapName = "China")
```

```{r}
x <- caculate_passcarsmean(jdnews,"province")
provincepassprevious <- caculate_passcarsmean(jdpreviouss,"province")
y <- caculate_increaseratio(x,provincepassprevious)
provincepasslast <- caculate_passcarsmean(jdlasts,"province")
z <- caculate_increaseratio(x,provincepasslast)
t <- merge_outcome(x,y,z,bywhat = "province")
names(t) <- c("省级行政区","月平均日交通量","同比","环比")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

### 6.4 货车交通量情况

```{r eval=FALSE}
caculate_frecarsmean(jdnews,"province") %>% 
geojsonMap(mapName = "China")
```

```{r}
x <- caculate_frecarsmean(jdnews,"province")
provincefreprevious <- caculate_frecarsmean(jdpreviouss,"province")
y <- caculate_increaseratio(x,provincefreprevious)
provincefrelast <- caculate_frecarsmean(jdlasts,"province")
z <- caculate_increaseratio(x,provincefrelast)
t <- merge_outcome(x,y,z,bywhat = "province")
names(t) <- c("省级行政区","月平均日交通量","同比","环比")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

## 8. 数据使用情况

```{r}
nrow(jdnews)
nrow(jdlasts)
nrow(jdpreviouss)
```


```{r}
t <- data_use(jdnews)[[1]]
rownames(t)[32] <- c("合计")
t <- t[,c("国家高速","普通国道","省级高速","普通省道")]
kable(t)
```

```{r}
p <- data_use(jdnews)[[2]]
kable(p)
```

```{r}
t$合计 <- rowSums(t)
t$省份 <- rownames(t)
t2 <- merge(t,province_region,by="省份")
tapply(t2$合计, t2$地域, sum)
```

