---
title: "Untitled"
author: "鐜嬭嚧杩<9c>"
date: "2018骞<b4>10鏈<88>9鏃<a5>"
output:
  word_document: default
  html_document: default
---

```{r}
options(stringsAsFactors = F)
options(digits = 3)
rm(list = ls())
source("D:\\R\\packages\\Mreport\\scripts\\caculate.R", encoding = "utf-8")
source("D:\\R\\packages\\Mreport\\scripts\\select.R", encoding = "utf-8")
source("D:\\R\\packages\\Mreport\\scripts\\split.R", encoding = "utf-8")
```

```{r}
library(Mreport)
library(plyr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(knitr)
library(leaflet)
library(leafletCN)
library(parallel)
```

```{r}
load_base()
load_sample_base()
```


```{r}
options(stringsAsFactors = F)
```


# 9月重点关注-国庆中秋专题

## 国庆节

```{r}
gq2018 <- read.csv("D:\\data\\sx_raw\\交调数据\\9月重点\\jdnational2018.csv")
gq2017 <- read.csv("D:\\data\\sx_raw\\交调数据\\9月重点\\jdnational2017.csv")
dim(gq2018)
dim(gq2017)
```

```{r}
years <- c(2018,2017,2016,2015,2014)
gqall <- list()
for(i in 1:length(years)){
  path <- paste(c("D:\\data\\sx_raw\\交调数据\\9月重点\\jdnational",years[i],".csv"),collapse="")
  gqall[[i]] <- read.csv(path)
}
names(gqall) <- years
```

```{r}
sapply(gqall, dim)
```

```{r}
gqalls <- lapply(gqall, handle_gather_formd)
gqalls <- lapply(gqalls, guoqing_transform)
```

```{r eval=FALSE}
usefulstation <- intersect(gqalls[[1]]$index,gqalls[[2]]$index)
gqalls <- lapply(gqalls,function(x) x[x[["index"]] %in% usefulstation,] )
```

```{r}
gq2018s <- gqalls[[1]]
gq2017s <- gqalls[[2]]
```


```{r}
x <- lapply(gqalls, caculate_carsmean, "md")
y <- Reduce(merge_list(bywhat="md"),x)
names(y)[2:6] <- names(x)
y
y <- melt(y)
```

```{r}
ggplot(y,aes(y$md,y$value,group=y$variable,color=y$variable))+geom_point()+geom_line()+
  labs(x="日期",y="平均交通量",colour="年份")
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\9月分析\\绘图\\近五年国庆节分日.png",dpi=600,height=4.5,width=9)
```

### 总量分析

```{r}
(x <- sapply(gqalls, caculate_all_cars))
```

```{r}
(x[1]-x[2])/x[2]
```


```{r}
(x <- sapply(gqalls, caculate_all_passcars))
```

```{r}
(x[1]-x[2])/x[2]
```

```{r}
(x <- sapply(gqalls, caculate_all_frecars))
```

```{r}
(x[1]-x[2])/x[2]
```

```{r}
result_present2(gq2018s,gq2017s,"level","cars")
```


### 按日分析

```{r}
result_present2(gq2018s,gq2017s,"md","cars") %>% arrange(md) %>% kable()
```


### 按道路等级

```{r}
caculate_carsmean(gq2018s,c("md","level")) %>% arrange(level) %>% dcast(md~level) %>% kable()
```

```{r}
x <- caculate_carsmean(gq2018s,c("md","level"))
ggplot(x,aes(x=md,y=Wmean,group=level,color=level))+geom_point()+geom_line()+
  labs(x="日期",y="平均日交通量",color="公路等级")+
  scale_y_continuous(breaks = c(0,50000,seq(0,50000,5000)))
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\9月分析\\绘图\\国庆节分公路等级交通量.png",dpi=600,height=4.5,width=9)
```

### 分车型

```{r}
(x <- caculate_passcarsmean(gq2018s,"md"))
```

```{r}
(y <- caculate_frecarsmean(gq2018s,"md"))
```

```{r}
z <- merge(x,y,by="md")
names(z)[2:3] <- c("客车交通量","货车交通量")
z <- melt(z)
```

```{r}
ggplot(z,aes(x=md,y=value,group=variable,color=variable))+geom_point()+geom_line()+
  ylim(5000,12000)+labs(x="日期",y="平均交通量",color="车类")
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\9月分析\\绘图\\国庆节分车类型交通量.png",dpi=600,height=4.5,width=9)
```


### 分省分析

```{r eval=FALSE}
caculate_carsmean(gq2018s,"province") %>% 
  geojsonMap("China",palette = "Reds",legendTitle = "交通量图例")
```


```{r}
x <- result_present2(gq2018s,gq2017s,"province","cars")
x$province <- factor(x$province,levels=province_level,ordered = T)
x <- arrange(x,province)
kable(x)
```


### 公路枢纽

```{r}
result_present2(gq2018s,gq2017s,"roadhub","cars") %>% kable()
```

```{r}
x <- caculate_carsmean(gq2018s,c("roadhub","md"))
ggplot(x,aes(x=md,y=Wmean,group=roadhub,colour=roadhub))+geom_point()+geom_line()+
  ylim(0,50000)+labs(x="日期",y="平均交通量",colour="区域")
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\9月分析\\绘图\\国庆节分区域交通量.png",dpi=600,height=4.5,width=9)
```


### 通道分析

```{r}
result_present2(gq2018s,gq2017s,"horizon10","cars") %>% kable()
```


```{r}
result_present2(gq2018s,gq2017s,"vertical10","cars") %>% kable()
```


### 城市群分析

```{r}
result_present2(gq2018s,gq2017s,"citygroup2","cars") %>% kable()
```

### 机场

```{r}
result_present2(gq2018s,gq2017s,"airport","cars") %>% kable()
```

### 省界

```{r}
result_present2(gq2018s,gq2017s,"provincedistinct","cars") %>% kable()
```

### 大城市出入口

```{r}
result_present2(gq2018s,gq2017s,"bigcityio","cars") %>% arrange(desc(now)) %>% kable()
```

### 旅游景区

```{r}
x <- result_present2(gq2018s,gq2017s,"scenery","cars")
t <- table(gq2018s$province,gq2018s$scenery) %>% as.data.frame()
t <- t[t$Freq!=0,c(1,2)]
names(t) <- c("province","scenery")
g <- merge(x,t,by="scenery")
g$province <- factor(g$province,ordered = T,levels=province_level)
g <- g[order(g$province),c(4,1,2,3)]
kable(g)
```


### 20条重点通道

```{r}
jd201820 <- read.csv("D:\\data\\sx_raw\\交调数据\\9月重点\\jdnational2018-20route.csv")
dim(jd201820)
```

```{r}
jd201820s <- handle_gather_formd_line(jd201820)
jd201820s <- guoqing_transform(jd201820s)
dim(jd201820s)
```

```{r}
x <- caculate_carsmean(jd201820s,c("lineindex","linename"))
x <- arrange(x,desc(Wmean))
kable(x)
```


```{r}
x <- caculate_carsmean(jd201820s,c("md","lineindex"))
dcast(x,md~lineindex)
```

```{r}
ggplot(x,aes(x=x$md,y=x$Wmean,color=x$lineindex,group=x$lineindex))+
  geom_point()+geom_line()+ylim(0,150000)+
  labs(x="日期",y="平均日交通量",color="公路等级")
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\9月分析\\绘图\\国庆节20条重要通道交通量.png",dpi=600,height=4.5,width=9)
```


