---
title: "20180716_月报分析通用模板"
author: "wzy"
date: "2018年7月16日"
output:
  word_document: default
  html_document: default
---

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F,message = F,warning = F)
```

```{r}
options(stringsAsFactors = F)
options(digits = 3)
rm(list = ls())
source("D:\\R\\packages\\Mreport\\scripts\\caculate.R", encoding = "utf-8")
source("D:\\R\\packages\\Mreport\\scripts\\select.R", encoding = "utf-8")
```

```{r}
library(Mreport)
library(plyr)
library(ggplot2)
library(reshape2)
library(knitr)
```

```{r}
load_base()
load_sample_base()
```

```{r include=FALSE}
jdnew <- read.csv("D:\\data\\sx_raw\\交调数据\\jd2018_06_new.csv")
jdlast <- read.csv("D:\\data\\sx_raw\\交调数据\\jd2018_05.csv")
jdprevious <- read.csv("D:\\data\\sx_raw\\交调数据\\jd2017_06.csv")
```

```{r include=FALSE}
jdnew <- caculate_equivalent(jdnew)
jdnew <- select_atts(jdnew)
jdnew <- handle_mergeline(jdnew,station_line)
jdnew <- handle_mergesample(jdnew,sample_base)
jdnew <- merge(jdnew,roadlevel,by="index",all.x = T)
jdnews <- subset(jdnew,index %in% station_use)
```

```{r include=FALSE}
jdlast <- caculate_equivalent(jdlast)
jdlast <- select_atts(jdlast)
jdlast <- handle_mergeline(jdlast,station_line)
jdlast <- handle_mergesample(jdlast,sample_base)
jdlast <- merge(jdlast,roadlevel,by="index",all.x = T)
jdlasts <- subset(jdlast,index %in% station_use)
```

```{r}
jdprevious <- caculate_equivalent(jdprevious)
jdprevious <- select_atts(jdprevious)
jdprevious <- handle_mergeline(jdprevious,station_line)
jdprevious <- handle_mergesample(jdprevious,sample_base)
jdprevious <- merge(jdprevious,roadlevel,by="index",all.x = T)
jdpreviouss <- subset(jdprevious,index %in% station_use)
```

```{r}
province_level <- c("北京市","天津市","河北省","山西省","内蒙古自治区","辽宁省","吉林省","黑龙江省",
                    "上海市","江苏省","浙江省","安徽省","福建省","江西省","山东省","河南省",
                    "湖北省","湖南省","广东省","广西壮族自治区","海南省","重庆市","四川省","贵州省",
                    "云南省","西藏自治区","陕西省","甘肃省","青海省","宁夏回族自治区","新疆维吾尔自治区")
```


## 2. 总体运行态势分析

### 2.1 机动车交通量情况

```{r}
totalnewcars <- ddply(jdnews,"level",summarise,Wmean = weighted.mean(cars,w=mileage))
totalpreviouscars <- ddply(jdpreviouss,"level",summarise,Wmean = weighted.mean(cars,w=mileage))
x <- caculate_increaseratio(totalnewcars,totalpreviouscars)
totallastcars <- ddply(jdlasts,"level",summarise,Wmean = weighted.mean(cars,w=mileage))
y <- caculate_increaseratio(totalnewcars,totallastcars)
z <- merge_outcome(totalnewcars,x,y,by="level")
temp <- z[3,]
z[3,] <- z[4,]
z[4,] <- temp
names(z) <- c("道路等级","本月","同比","环比")
kable(z)
```

### 2.2 客运车辆交通量情况

```{r}
totalnewpasscars <- ddply(jdnews,"level",summarise,Wmean = weighted.mean(passenger_cars,w=mileage))
totalpreviouspasscars <- ddply(jdpreviouss,"level",summarise,Wmean = weighted.mean(passenger_cars,w=mileage))
x <- caculate_increaseratio(totalnewpasscars,totalpreviouspasscars)
totallastpasscars <- ddply(jdlasts,"level",summarise,Wmean = weighted.mean(passenger_cars,w=mileage))
y <- caculate_increaseratio(totalnewpasscars,totallastpasscars)
z <- merge_outcome(totalnewpasscars,x,y,by="level")
temp <- z[3,]
z[3,] <- z[4,]
z[4,] <- temp
names(z) <- c("道路等级","本月","同比","环比")
kable(z)
```

### 2.3 货运车辆交通量情况

```{r}
totalnewfrecars <- ddply(jdnews,"level",summarise,Wmean = weighted.mean(freight_cars,w=mileage))
totalpreviousfrecars <- ddply(jdpreviouss,"level",summarise,Wmean = weighted.mean(freight_cars,w=mileage))
x <- caculate_increaseratio(totalnewfrecars,totalpreviousfrecars)
totallastfrecars <- ddply(jdlasts,"level",summarise,Wmean = weighted.mean(freight_cars,w=mileage))
y <- caculate_increaseratio(totalnewfrecars,totallastfrecars)
z <- merge_outcome(totalnewfrecars,x,y,by="level")
temp <- z[3,]
z[3,] <- z[4,]
z[4,] <- temp
names(z) <- c("道路等级","本月","同比","环比")
kable(z)
```

## 3. 省级行政区路网运行情况

### 3.1 各省机动车交通量情况

#### 本月

```{r eval=FALSE}
caculate_carsmean(jdnews,"province") %>% 
geojsonMap(mapName = "China")
```

```{r}
t <- caculate_carsmean(jdnews,"province")
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

```{r}
caculate_carsmean(jdnews,"province") %>% gg_boxplot(xangle = 90,xlabname = "省级行政区",
                                                    ylabname="月平均日机动车交通量")
ggsave(filename = "D:\\交大云同步\\实习\\06_月度分析报告\\6月分析\\绘图\\省级机动车.jpg",dpi=600)
```

#### 同比

```{r}
t <- caculate_increaseratio(caculate_carsmean(jdnews,"province"),
                       caculate_carsmean(jdpreviouss,"province"))
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

#### 环比

```{r}
t <- caculate_increaseratio(caculate_carsmean(jdnews,"province"),
                       caculate_carsmean(jdlasts,"province"))
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

### 3.2 各省分道路等级交通量情况

#### 本月

```{r, results="asis"}
provincenewcars <- caculate_level_carsmean(jdnews,"province")
kable(provincenewcars)
```

#### 同比

```{r}
provincepreviouscars <- caculate_level_carsmean(jdpreviouss,"province")
caculate_increaseratio(provincenewcars,provincepreviouscars) %>% kable()
```

#### 环比

```{r}
provincelastcars <- caculate_level_carsmean(jdlasts,"province")
caculate_increaseratio(provincenewcars,provincelastcars) %>% kable()
```

### 3.3 各省客运车辆

#### 本月

```{r}
t <- provincepassnew <- caculate_passcarsmean(jdnews,"province")
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

```{r eval=FALSE}
caculate_passcarsmean(jdnews,"province") %>% 
geojsonMap(mapName = "China")
```

#### 同比

```{r}
provincepassprevious <- caculate_passcarsmean(jdpreviouss,"province")
t <- caculate_increaseratio(provincepassnew,provincepassprevious)
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

#### 环比

```{r}
provincepasslast <- caculate_passcarsmean(jdlasts,"province")
t <- caculate_increaseratio(provincepassnew,provincepasslast)
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

### 3.4 各省货运车辆

#### 本月

```{r}
t <- provincefrenew <- caculate_frecarsmean(jdnews,"province")
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

```{r eval=FALSE}
caculate_frecarsmean(jdnews,"province") %>% 
geojsonMap(mapName = "China")
```

#### 同比

```{r}
provincefreprevious <- caculate_frecarsmean(jdpreviouss,"province")
t <- caculate_increaseratio(provincefrenew,provincefreprevious)
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

#### 环比

```{r}
provincefrelast <- caculate_frecarsmean(jdlasts,"province")
t <- caculate_increaseratio(provincefrenew,provincefrelast)
names(t) <- c("省级行政区","月平均日交通量")
t$省级行政区 <- factor(t$省级行政区,ordered=T,levels = province_level)
kable(t[order(t$省级行政区),])
```

## 4. 城市群分析

站点在各个城市群的分布如下：

```{r eval=FALSE}
t <- merge(station_plot,sample_base$citygroup2,by.x = "popup",by.y = "index",all.y = T)
names(t)[5] <- "type"
geo_pointplot(t,na.rm=T,type = T)
```

### 4.1 总体

```{r}
x <- caculate_carsmean(jdnews,"citygroup2")
```

```{r}
x1 <- caculate_increaseratio(caculate_carsmean(jdnews,"citygroup2"),
                       caculate_carsmean(jdpreviouss,"citygroup2"))
```

```{r}
x2 <- caculate_increaseratio(caculate_carsmean(jdnews,"citygroup2"),
                       caculate_carsmean(jdlasts,"citygroup2"))
```

```{r}
t <- merge_outcome(x,x1,x2,bywhat = "citygroup2")
names(t) <- c("城市群","月平均日交通量","同比","环比")
kable(t)
```


### 4.2 客车

```{r}
x <- caculate_passcarsmean(jdnews,"citygroup2")
```

```{r}
x1 <- caculate_increaseratio(caculate_passcarsmean(jdnews,"citygroup2"),
                       caculate_passcarsmean(jdpreviouss,"citygroup2"))
```

```{r}
x2 <- caculate_increaseratio(caculate_passcarsmean(jdnews,"citygroup2"),
                       caculate_passcarsmean(jdlasts,"citygroup2"))
```

```{r}
t <- merge_outcome(x,x1,x2,bywhat = "citygroup2")
names(t) <- c("城市群","月平均日交通量","同比","环比")
kable(t)
```

### 4.3 货车

```{r}
x <- caculate_frecarsmean(jdnews,"citygroup2")
```

```{r}
x1 <- caculate_increaseratio(caculate_frecarsmean(jdnews,"citygroup2"),
                       caculate_frecarsmean(jdpreviouss,"citygroup2"))
```

```{r}
x2 <- caculate_increaseratio(caculate_frecarsmean(jdnews,"citygroup2"),
                       caculate_frecarsmean(jdlasts,"citygroup2"))
```

```{r}
t <- merge_outcome(x,x1,x2,bywhat = "citygroup2")
names(t) <- c("城市群","月平均日交通量","同比","环比")
kable(t)
```

## 5. 通道分析

### 5.1 十横通道

```{r}
horizonnew <- caculate_carsmean(jd = jdnews,attsname = "horizon10")
```

```{r}
horizonprevious <- caculate_carsmean(jd = jdpreviouss,attsname = "horizon10")
x1 <- caculate_increaseratio(horizonnew,horizonprevious)
```

```{r}
horizonlast <- caculate_carsmean(jd = jdlasts,attsname = "horizon10")
x2 <- caculate_increaseratio(horizonlast,horizonprevious)
```

```{r}
t <- merge_outcome(horizonnew,x1,x2,bywhat = "horizon10")
names(t) <- c("十横通道","月平均日交通量","同比","环比")
kable(t)
```

### 5.2 十横重点关注通道交通量情况

#### 5.2.1 沪昆通道

```{r}
x <- subset(jdnews,horizon10 == "上海-瑞丽")
x <- ddply(x,c("horizon10","province"),
                     summarise,Wmean = weighted.mean(cars,w=mileage))
x <- na.omit(x)
names(x) <- c("沪昆通道","省份","月平均日交通量")
x %>% kable()
```

#### 5.2.2 陆桥通道

```{r}
x <- subset(jdnews,horizon10 == "连云港-霍尔果斯")
x <- ddply(x,c("horizon10","province"),
                     summarise,Wmean = weighted.mean(cars,w=mileage))
x <- na.omit(x)
names(x) <- c("路桥通道","省份","月平均日交通量")
x %>% kable()
```

#### 5.2.3 沿江通道

```{r}
x <- subset(jdnews,horizon10 == "上海-樟木")
x <- ddply(x,c("horizon10","province"),
                     summarise,Wmean = weighted.mean(cars,w=mileage))
x <- na.omit(x)
names(x) <- c("沿江通道","省份","月平均日交通量")
x %>% kable()
```

### 5.3 十纵通道交通量情况

十纵通道

```{r}
verticalnew <- caculate_carsmean(jd = jdnews,attsname = "vertical10")
```

```{r}
gg_boxplot(verticalnew,xangle = 15,xlabname = "十横通道",ylabname = "平均机动车当量")
```

```{r}
verticalprevious <- caculate_carsmean(jd = jdpreviouss,attsname = "vertical10")
x1 <- caculate_increaseratio(verticalnew,verticalprevious)
```

```{r}
verticallast <- caculate_carsmean(jd = jdlasts,attsname = "vertical10")
x2 <- caculate_increaseratio(verticallast,verticalprevious)
```

```{r}
t <- merge_outcome(verticalnew,x1,x2,bywhat = "vertical10")
names(t) <- c("十横通道","月平均日交通量","同比","环比")
kable(t)
```

### 5.4 十纵重点通道

#### 5.4.1 京沪通道

```{r}
x <- subset(jdnews,vertical10 == "北京-上海")
x <- ddply(x,c("vertical10","province"),
                     summarise,Wmean = weighted.mean(cars,w=mileage))
x <- na.omit(x)
x %>% kable()
```

#### 5.4.2 沿海通道

```{r}
x <- subset(jdnews,vertical10 == "同江-三亚")
x <- ddply(x,c("vertical10","province"),
                     summarise,Wmean = weighted.mean(cars,w=mileage))
x <- na.omit(x)
x %>% kable()
```

#### 5.4.3 黑河至港澳台通道

```{r}
x <- subset(jdnews,vertical10 == "黑河-港澳台")
x <- ddply(x,c("vertical10","province"),
                     summarise,Wmean = weighted.mean(cars,w=mileage))
x <- na.omit(x)
x %>% kable()
```

## 6. 疏港公路分析

```{r}
portroadnew <- caculate_carsmean(jdnews,attsname = "portroad")
```

```{r}
gg_boxplot(portroadnew,xangle = 20,xlabname = "疏港公路",ylabname = "平均机动车当量")
```


```{r}
portroadprevious <- caculate_carsmean(jdprevious,attsname = "portroad")
x1 <- caculate_increaseratio(portroadnew,portroadprevious)
```

```{r}
portroadlast <- caculate_carsmean(jdlasts,attsname = "portroad")
x2 <- caculate_increaseratio(portroadnew,portroadlast)
```

```{r}
merge_outcome(portroadnew,x1,x2,bywhat = "portroad") %>% kable()
```

## 数据使用情况

```{r}
table(jdnews$province,jdnews$level) %>% kable()
```

