---
title: "20181108_10_important"
author: "鐜嬭嚧杩<9c>"
date: "2018骞<b4>11鏈<88>8鏃<a5>"
output:
  word_document: default
  html_document: default
---

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F,message = F,warning = F)
```

```{r}
options(stringsAsFactors = F)
options(digits = 3)
rm(list = ls())
source("D:\\R\\packages\\Mreport\\scripts\\caculate.R", encoding = "utf-8")
source("D:\\R\\packages\\Mreport\\scripts\\select.R", encoding = "utf-8")
source("D:\\R\\packages\\Mreport\\scripts\\split.R", encoding = "utf-8")
```

```{r}
library(Mreport)
library(plyr)
library(ggplot2)
library(reshape2)
library(knitr)
library(leaflet)
library(leafletCN)
library(dplyr)
library(stringr)
library(RColorBrewer)
```

```{r}
load_base()
load_sample_base()
```

## 7. 十月重点关注


## 7.1 港珠澳大桥开通运行前后交通量变化

### 分日

```{r}
xzyk_day <- read.csv("D:\\data\\sx_raw\\交调数据\\10月重点\\XZYK_day.csv",stringsAsFactor=F)
dim(xzyk_day)
```

```{r}
xzyk_mds <- handle_gather_formd(xzyk_day)
dim(xzyk_mds)
```


```{r}
xzyk_mds$md <- factor(xzyk_mds$md,level=as.character(xzyk_mds$md),order=T)
```


```{r}
ggplot(data = xzyk_mds,aes(x=md,y=cars))+
  geom_point(color="steelblue")+
  geom_line(group=1,color="steelblue")+
  scale_x_discrete(breaks=xzyk_mds$md[seq(5,37,7)])+
  labs(x="日期",y="日平均交通量")
```

```{r}
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\10月分析\\绘图\\香洲银坑分日.png",dpi=600,height=4.5,width=9)
```


### 分小时

```{r}
xzyk_hour <- read.csv("D:\\data\\sx_raw\\交调数据\\10月重点\\XZYK_hour.csv",stringsAsFactor=F)
dim(xzyk_hour)
```

```{r}
names(xzyk_hour)
```

```{r}
xzyk_hours <- handle_gather_formdh(xzyk_hour)
```

```{r}
xzyk_hours$tf <- F
xzyk_hours$tf[xzyk_hours$md %in% c("10-21","10-27","10-28")] <- T
```

```{r}
xzyk_hours$tf[xzyk_hours$md<="10-25"] <- "开通前"
xzyk_hours$tf[xzyk_hours$md=="10-26"] <- "最高峰日"
xzyk_hours$tf[xzyk_hours$md>"10-26"] <- "开通后"
```

```{r}
ggplot(xzyk_hours,aes(x=hour,y=cars,group=md,color=tf))+geom_point(alpha=0.7)+geom_line(alpha=0.3)+
  scale_x_continuous(breaks = seq(1,24,2))+
  labs(x="小时",y="机动车交通量",color="开通前后")
```

```{r}
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\10月分析\\绘图\\香洲银坑分小时.png",dpi=600,height=4.5,width=9)
```


## 7.2 货车交通量分析

```{r}
plot_frecars <- function(jdlist, attsname) {
  result <- ldply(jdlist, caculate_frecarsmean, attsname)
  result_plot <- ggplot(result,aes(x=result[[".id"]],y=result[["Wmean"]],
                            group=result[[attsname]],color=result[[attsname]]))+geom_point()+geom_line()
  return(result_plot)
}
```


```{r}
months <- 201801:201810
jdall <- list()
for(i in 1:length(months)){
  path <- paste(c("D:\\data\\sx_raw\\交调数据\\jd",months[i],".csv"),collapse = "")
  jdall[[i]] <- read.csv(path)
}
names(jdall) <- months
```


```{r}
sapply(jdall, dim)
```

```{r}
jdalls <- lapply(jdall, handle_gather)
```

```{r}
l <- lapply(jdalls,`[[`,"index")
usefulstation <- Reduce(intersect,l)
length(usefulstation)
```


```{r}
jdalls <- lapply(jdalls, function(x) filter(x,index %in% usefulstation))
```

```{r}
sapply(jdalls, dim)
```


### 1. 总体情况

#### 总量分析

```{r}
sapply(jdalls,caculate_all_frecars)
```

#### 分等级分析


```{r}
ldply(jdalls, caculate_frecarsmean, "level") %>% dcast(.id~level) %>% kable()
```

### 2. 面

#### 分区域分析

```{r}
ldply(jdalls, caculate_frecarsmean, "roadhub") %>% dcast(.id ~ roadhub) %>% kable()
```

```{r}
ldply(jdalls, caculate_frecarsmean, "roadhub") %>% mutate(month=str_sub(.id,-2,-1)) %>% 
  ggplot(aes(x=month,y=Wmean,group=roadhub,color=roadhub))+geom_point()+geom_line()+
  labs(x="月份",y="月均日交通量",color="区域")
```

```{r}
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\10月分析\\绘图\\分区域.png",dpi=600,height=4.5,width=9)
```


#### 分城市群分析

```{r}
ldply(jdalls, caculate_frecarsmean, "citygroup2") %>% dcast(citygroup2~.id) %>% kable()
```

```{r}
ldply(jdalls, caculate_frecarsmean, "citygroup2") %>% mutate(month=str_sub(.id,-2,-1)) %>% 
  ggplot(aes(x=month,y=Wmean,group=citygroup2,color=citygroup2))+geom_point()+geom_line()+
  labs(x="月份",y="月均日交通量",color="城市群")
```

```{r}
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\10月分析\\绘图\\城市群.png",dpi=600,height=4.5,width=9)
```


#### 分省分析

```{r}
t <- ldply(jdalls, caculate_frecarsmean, "province") %>% dcast(province~.id)
t <- cbind(t[1],rowMeans(cbind(t[7],t[8],t[9],t[10],t[11]))-rowMeans(cbind(t[2],t[3],t[4],t[5],t[6])))
names(t) <- c("province","diff")
t <- t[t$province!="上海市",]
t %>% kable()
```


```{r eval=FALSE}
pal <- colorBin(palette = rev(brewer.pal(n=9,name = "RdYlBu")),domain = t$diff)
map <- leafletGeo("China",t)
leaflet(map) %>% amap() %>%
  addPolygons(stroke = TRUE,
                smoothFactor = 1,
                fillOpacity = 0.7,
                weight = 1,
                color = ~pal(value),
                popup = ~htmltools::htmlEscape(popup)
    ) %>%
    #加入右下角边框
    addLegend("bottomright", pal = pal, values = ~value,
              title = "货车交通量变化量",
              labFormat = leaflet::labelFormat(prefix = ""),
              opacity = 1)
```

### 3. 通道

#### 十纵

```{r}
ldply(jdalls, caculate_frecarsmean, "vertical10") %>% dcast(vertical10~.id) %>% kable()
```

```{r}
ldply(jdalls, caculate_frecarsmean, "vertical10") %>% mutate(month=str_sub(.id,-2,-1)) %>%
  ggplot(aes(x=month,y=Wmean,group=1))+geom_point(color="steelblue")+geom_line(color="steelblue")+
  facet_wrap(~vertical10,nrow=2)+
  theme(axis.text.x=element_text(hjust = 0.5,angle=90))+
  labs(x="月份",y="月均日交通量")
```

```{r}
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\10月分析\\绘图\\十纵.png",dpi=600,height=4.5,width=9)
```


#### 十横

```{r}
ldply(jdalls, caculate_frecarsmean, "horizon10") %>% dcast(horizon10~.id) %>% kable()
```

```{r}
ldply(jdalls, caculate_frecarsmean, "horizon10") %>% mutate(month=str_sub(.id,-2,-1)) %>%
  ggplot(aes(x=month,y=Wmean,group=1))+geom_point(color="steelblue")+geom_line(color="steelblue")+
  facet_wrap(~horizon10,nrow=2)+
  theme(axis.text.x=element_text(angle = 90))+
  labs(x="月份",y="月均日交通量")
```

```{r}
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\10月分析\\绘图\\十横.png",dpi=600,height=4.5,width=9)
```


#### 4. 点

```{r}
ldply(jdalls, caculate_frecarsmean, "portroad") %>% 
  dcast(portroad~.id) %>% kable()
```


```{r fig.height=12,fig.width=12}
ldply(jdalls, caculate_frecarsmean, "portroad") %>% 
  ggplot(aes(x=.id,y=Wmean,group=1))+geom_point(color="steelblue")+geom_line(color="steelblue")+
  facet_wrap(~portroad,nrow=4,scales = "free_y")+
  theme(axis.text.x=element_text(angle = 90))+
  labs(x="月份",y="月均日交通量")
```

```{r}
ggsave(file="D:\\交大云同步\\实习\\06_月度分析报告\\10月分析\\绘图\\疏港公路.png",dpi=600,height=8,width=14)
```

