---
title: "20180920_货运计算1"
author: "wzy"
date: "2018年9月20日"
output: html_document
---

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F,message = F,warning = F)
```

```{r}
options(stringsAsFactors = F)
options(digits = 3)
rm(list = ls())
source("D:\\R\\packages\\Mreport\\scripts\\caculate.R", encoding = "utf-8")
source("D:\\R\\packages\\Mreport\\scripts\\select.R", encoding = "utf-8")
source("D:\\R\\packages\\Mreport\\scripts\\split.R", encoding = "utf-8")
```

```{r}
library(Mreport)
library(plyr)
library(ggplot2)
library(reshape2)
library(knitr)
library(leaflet)
library(leafletCN)
```

```{r}
load_base()
load_sample_base()
```

## 1. 核心城市

### 货车行驶量

```{r}
jdcity <- read.csv("D:\\data\\sx_raw\\交调数据\\jdcity.csv",stringsAsFactors = F)
```

```{r}
jdcitys <- handle_gather_forym(jdcity)
```

```{r}
jdcitys <- jdcitys[jdcitys$ym != "2018-09月",]
```


```{r}
x <- caculate_frecarsmean(jdcitys,c("ym","province","level")) %>% dcast(ym+province~level)
x <- x[,c(1,2,3,4,6,5)]
head(x,10)
```

```{r}
x2 <- caculate_travel_volume(x,mileage,"province")
x2$武汉市 <- x2$湖北省/9
x2$湖北省 <- NULL
x2
```

```{r}
write.csv(x2,file = "D:\\交大云同步\\实习\\19_货运分析\\计算结果\\三市月平均日总行驶量.csv")
```


### 货车出行量

```{r}
x3 <- caculate_freight_trip(x,mileage,"province")
x3$武汉市 <- x3$湖北省/9
x3$湖北省 <- NULL
x3
```

```{r}
write.csv(x3,file = "D:\\交大云同步\\实习\\19_货运分析\\计算结果\\三市月平均日货车出行次数.csv")
```


## 2. 重点运输通道

```{r}
jdg60 <- read.csv("D:\\data\\sx_raw\\交调数据\\jdG60.csv",stringsAsFactors = F)
dim(jdg60)
```

```{r}
jdg60s <- handle_gather_forym(jdg60)
```

```{r}
jdg60s <- jdg60s[jdg60s$ym != "2018-09月",]
```

```{r}
names(jdg60s)
```

### 断面交通量

```{r}
x <- caculate_frecarsmean(jdg60s,c("ym","level")) %>% dcast(ym~level)
x
```

```{r}
write.csv(x,file="D:\\交大云同步\\实习\\19_货运分析\\计算结果\\G60断面交通量.csv")
```


### 货车出行次数

G60高速全长2730km

```{r}
x2 <- x
x2[2] <- x[2]*2730;x2
```

### 货运量

```{r}
x3 <- x2
x3[2] <- x2[2]*16.754;x3
```


## 3. 东中西三部分

```{r}
jdprovince <- read.csv("D:\\data\\sx_raw\\交调数据\\jdprovince.csv",stringsAsFactors = F)
dim(jdprovince)
```

```{r}
jdprovinces <- handle_gather_forym(jdprovince)
```


```{r}
jdprovinces <- jdprovinces[jdprovinces$ym != "2018-09月",]
```

```{r}
x <- caculate_frecarsmean(jdprovinces,c("ym","province","level")) %>% dcast(ym+province~level)
x <- x[,c(1,2,3,4,6,5)]
head(x,10)
```

### 货车行驶量

```{r}
x2 <- caculate_travel_volume(x,mileage,"province")
x2
```

```{r}
write.csv(x2,file="D:\\交大云同步\\实习\\19_货运分析\\计算结果\\东中西11省月均日货车行驶量.csv")
```

### 货车出行量

```{r}
x3 <- caculate_freight_trip(x,mileage,"province")
x3
```

```{r}
write.csv(x3,file="D:\\交大云同步\\实习\\19_货运分析\\计算结果\\东中西11省月均日货车出行量.csv")
```

### 货运量

```{r}
x4 <- x3*16.754
x4
```

```{r}
write.csv(x4,file="D:\\交大云同步\\实习\\19_货运分析\\计算结果\\东中西11省月均日货运量.csv")
```

## 4. 疏港公路

重庆港朝天门码头附近没有交调站

```{r}
unique(sample_base$portroad$V1)
```

```{r}
portroad <- sample_base$portroad
portroad[portroad$V1 == "上海港",]
```

```{r}
portroad <- sample_base$portroad
portroad[portroad$V1 == "南京港",]
```

```{r}
jdport <- read.csv("D:\\data\\sx_raw\\交调数据\\jdport.csv",stringsAsFactors = F)
dim(jdport)
```

```{r}
names(jdport)
```

```{r}
jdports <- handle_gather_forym(jdport)
```

```{r}
jdports <- jdports[jdports$ym != "2018-09月",]
```

```{r}
names(jdports)
```

```{r}
x <- caculate_frecarsmean(jdports,c("ym","city")) %>% dcast(ym~city)
x
```

```{r}
write.csv(x,file = "D:\\交大云同步\\实习\\19_货运分析\\计算结果\\上海港南京港平均日断面交通量.csv")
```

