---
title: "20180625_jd201805探索"
author: "wzy"
date: "2018年6月25日"
output: html_document
---

```{r}
options(stringsAsFactors = F)
```

```{r}
library(Mreport)
library(ggplot2)
```

```{r}
load_base()
load_sample_base()
```


```{r}
jd201805 <- read.csv("D:\\data\\sx_raw\\交调数据\\jd2018_05.csv")
dim(jd201805)
```

```{r}
jd201805 <- caculate_equivalent(jd201805)
```

```{r}
jd201805s <- select_atts(jd201805)
```


```{r}
jd201805all <- handle_mergeline(jd201805s,station_line)
```


```{r}
jd <- handle_mergesample(jd201805all,sample_base)
names(jd)
```

```{r}
arrange(aggregate(cars~roadhub,data=jd,FUN = mean),cars)
```

```{r}
arrange(aggregate(cars~airport,data=jd,FUN = mean),cars)
```

```{r}
arrange(aggregate(cars~vertical10,data=jd,FUN = mean),cars)
```

```{r}
arrange(aggregate(cars~citygroup,data=jd,FUN = mean),cars)
```

```{r}
arrange(aggregate(cars~bigcityio,data=jd,FUN = mean),cars)
```

```{r}
x <- arrange(aggregate(cars~province,data=jd,FUN = mean),cars);x
```

```{r}
arrange(aggregate(crowd~citygroup,data=jd,FUN = mean),crowd)
```



